# Generated by Django 5.0.4 on 2024-07-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='face',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('faceSave', models.ImageField(upload_to='D:\\summerProject2024\x0bideo\x0caceRecog\\images\\')),
            ],
        ),
    ]
