# Generated by Django 5.0.4 on 2024-07-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userLogin", "0004_warn"),
    ]

    operations = [
        migrations.AddField(
            model_name="warn",
            name="done",
            field=models.IntegerField(default=0),
        ),
    ]
